/*
<#include "MicrochipDisclaimer.ftl">
*/

#include "nRFCDrivers/nRFC.h"
#include "device_config.h"
#include "${SPIFunctions["spiHeader"]}"
#include "${SPIFunctions["spiTypesHeader"]}"
#include "${pinHeader}"
#ifdef __XC
#include <xc.h>
#endif
#include <stdio.h>

<#if nRFC_ModeKey == "Transmit">
// Deal with interrupts generated by a transmit
void Transmit_Interrupt_Handler() {
    uint8_t stat = Read_Status();
    
    // if transmit failed due to max retries, retry again
    if (stat & MAX_RT_MASK) {
        nRFC_PowerUp_LAT = 1;
        while (stat & MAX_RT_MASK) {
            Retry_Transmit();
            while (nRFC_Interrupt_PORT) {
                NOP();
            }
            stat = Read_Status();
        }
        nRFC_PowerUp_LAT = 0;
    }

    // if transmit went through, clear indicator
    if (stat & TX_DS_MASK) {
        Clear_Interrupt(TX_DS_MASK);
    }
}

// transmitter example code
void transmitter() {
    Setup_Transmitter();
    uint8_t payload[7] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
    <#if (isAVR == "true")>
    _delay_ms(100);
    <#else>
    __delay_ms(100);
    </#if>
    while (1) {
        nRFC_PowerUp_LAT = 1;

        // Load payload to the nRF C
        Upload_Tx_Payload(payload, 7);

        // Wait for an interrupt to indicate transmit completed, then turn off transmit
        while (nRFC_Interrupt_PORT) {
            NOP();
        }
        nRFC_PowerUp_LAT = 0;

        // Handle the interrupt
        Transmit_Interrupt_Handler();
        <#if (isAVR == "true")>
		_delay_ms(100);
		<#else>
		__delay_ms(100);
		</#if>
        if (!nRFC_Interrupt_PORT) {
            Transmit_Interrupt_Handler();
        }
    }
}
</#if>

<#if nRFC_ModeKey == "Receive">
void receiver() {
    Setup_Receiver();
    while (1) {
        while (nRFC_Interrupt_PORT) {
            NOP();
        }
        Download_Rx_Payload();
        uint8_t i = 0;
        printf("Packet: ");
        for(i = 0; i < Rx_Buffer_Size; i++){
            printf("%d ", Rx_Buffer[i]);
        }
        printf("\n");
        
    }
}
</#if>